[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Required Environment Variables (set these in Netlify UI):
# NEXTAUTH_SECRET - Secret key for NextAuth
# NEXTAUTH_URL - Your Netlify site URL (e.g., https://your-site.netlify.app)
# NEXT_PUBLIC_API_URL - Your Netlify site URL (e.g., https://your-site.netlify.app)

[[plugins]]
  package = "@netlify/plugin-nextjs"

